// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqP1zoAkbNjuXKwBg_GpRq0RIPK2_FCjY',
    appId: '1:841940603859:web:2a0ced54f96378194e1526',
    messagingSenderId: '841940603859',
    projectId: 'test-2eb44',
    authDomain: 'test-2eb44.firebaseapp.com',
    storageBucket: 'test-2eb44.appspot.com',
    measurementId: 'G-BGSPJ6Z68H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIySxr1zd8seBIAq65VOYNGkCBvj6SmP4',
    appId: '1:841940603859:android:8791f7f5aee70d714e1526',
    messagingSenderId: '841940603859',
    projectId: 'test-2eb44',
    storageBucket: 'test-2eb44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj3rTfPiaBAUpkoC1rcpApYBgRylimQKk',
    appId: '1:841940603859:ios:b6fb867d2917d85b4e1526',
    messagingSenderId: '841940603859',
    projectId: 'test-2eb44',
    storageBucket: 'test-2eb44.appspot.com',
    iosClientId: '841940603859-k8cuctcubujot2fmpepnmautndib9bda.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj3rTfPiaBAUpkoC1rcpApYBgRylimQKk',
    appId: '1:841940603859:ios:b6fb867d2917d85b4e1526',
    messagingSenderId: '841940603859',
    projectId: 'test-2eb44',
    storageBucket: 'test-2eb44.appspot.com',
    iosClientId: '841940603859-k8cuctcubujot2fmpepnmautndib9bda.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
